{% set version = "0.4" %}

package:
  name: entrypoints
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/entrypoints/entrypoints-{{ version }}.tar.gz
  sha256: b706eddaa9218a19ebcd67b56818f05bb27589b1ca9e8d797b74affad4ccacd4

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - entrypoints

about:
  home: https://entrypoints.readthedocs.io/
  license: MIT
  license_file: LICENSE
  summary: Discover and load entry points from installed packages

extra:
  recipe-maintainers:
    - pelson
    - minrk
    - takluyver
    - ocefpaf
