travis:
  secure:
    BINSTAR_TOKEN: g3wOSaKiJzA/4GY55ntqjrrsvXJfnLldonLl1kwZcBP+bqH/tmeX3T08zZJrwQVFKSRt2TpeYHoXgLsqP0bjHGrIIToENMVjZvCPPIzXrWHC1E/BScIiAXjdSmXWs53e8GkMd4suoSvPi0bbAOM1lth/SJVgzwBeYyy/4gnPs51VZhbfyoIITK6rLRWH8HwUBePRffNNRJVOWkrSP4GAdiwjIkKfcUBinjThErD00j6+wEsvpEo5Dinga7YoZqIfY2fRd9z11HHHBBlUz9sOmaK07ECqIviZrsltT37tstk3yrFqc4AAfJOyqlr8YH5gtBoZ5NFoM+RDezmf97oubucp+Me9j1eQY5PhGYGEp7chPZ1dibxc6KHxAW7lE6NbcpeWwK0vTA/6UAcaClPaC/mLPsM6kcV6wakh8BQHh7DRc7ZMk9LWm7YzM+f2V17OXt7zc84HF0IHO8dEexjrLJLJ4VFiZYf4/5jVehgFzfxwPreI7JkSv1b/nIukqXhEma1Ws9GrBCvxAWrnA0JgmVtu7HHevD/JBI1PgvpYyqOXbnK0HMoKI33p721+zw1Nw5RqD+LiiHe0bjrk+sXVjtgWgMwo9RNz5eTqxy0/PPyz4MfibWWsGZhKCOgxteBnIyUSX4P1F+GARw4rIE4pLOPO5AwMVg/hIW46cW9mbGY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
